# FROM nginx:latest

# WORKDIR /html

# COPY index.html /html

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]


#test1 ubuntu

# FROM ubuntu:latest

# RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y ubuntu-desktop lightdm

# RUN rm /run/reboot-required*
# RUN echo "/usr/sbin/lightdm" > /etc/X11/default-display-manager
# RUN echo "\
# [LightDM]\n\
# [Seat:*]\n\
# type=xremote\n\
# xserver-hostname=host.docker.internal\n\
# xserver-display-number=0\n\
# autologin-user=root\n\
# autologin-user-timeout=0\n\
# " > /etc/lightdm/lightdm.conf.d/lightdm.conf

# ENV DISPLAY=host.docker.internal:0.0

# CMD service dbus start ; /usr/lib/systemd/systemd-logind & service lightdm start

#test2 lubuntu
FROM ubuntu:latest

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y lubuntu-desktop lightdm

RUN rm /run/reboot-required*
RUN echo "/usr/sbin/lightdm" > /etc/X11/default-display-manager
RUN echo "\
[LightDM]\n\
[Seat:*]\n\
type=xremote\n\
xserver-hostname=host.docker.internal\n\
xserver-display-number=0\n\
autologin-user=root\n\
autologin-user-timeout=0\n\
autologin-session=Lubuntu\n\
" > /etc/lightdm/lightdm.conf.d/lightdm.conf

ENV DISPLAY=host.docker.internal:0.0

CMD service dbus start ; service lightdm start